src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="The entred email is already used")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="5",minMessage="Your password is too short")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password",message="Please verify the entred password")
     */
    private $confirm_password;

    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }

    /**
     * @param mixed $confirm_password
     */
    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Length(min="8",max="8",exactMessage="This phone number is invalid")
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Length(min="1")
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profession;

    /**
     * @ORM\ManyToOne(targetEntity=Gender::class, inversedBy="users",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $gender;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $about;


    /**
     * @ORM\Column(type="string" , length=255)
     * @Assert\Url()
     */
    private $image ;

    /**
     * @ORM\OneToOne(targetEntity=Announcement::class, inversedBy="userColoc", cascade={"persist", "remove"})
     */
    private $coloc;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Announcement::class, mappedBy="UserOwner")
     */
    private $announcements;

    /**
     * @ORM\ManyToOne(targetEntity=Announcement::class, inversedBy="colloc")
     */
    private $appliedAnn;





    public function __construct()
    {
        $this->owner = new ArrayCollection();
        $this->announcements = new ArrayCollection();
    }


    /**
     * Permet l'initialisation du slug
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     * @return void
     */

    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->username);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(int $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): self
    {
        $this->about = $about;

        return $this;
    }



    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image ): self
    {

            $this->image = $image;

        return $this;
    }

    public function getColoc(): ?Announcement
    {
        return $this->coloc;
    }

    public function setColoc(?Announcement $coloc): self
    {
        $this->coloc = $coloc;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Announcement[]
     */
    public function getAnnouncements(): Collection
    {
        return $this->announcements;
    }

    public function addAnnouncement(Announcement $announcement): self
    {
        if (!$this->announcements->contains($announcement)) {
            $this->announcements[] = $announcement;
            $announcement->setUser($this);
        }

        return $this;
    }

    public function removeAnnouncement(Announcement $announcement): self
    {
        if ($this->announcements->contains($announcement)) {
            $this->announcements->removeElement($announcement);
            // set the owning side to null (unless already changed)
            if ($announcement->getUser() === $this) {
                $announcement->setUser(null);
            }
        }

        return $this;
    }

    public function getAppliedAnn(): ?Announcement
    {
        return $this->appliedAnn;
    }

    public function setAppliedAnn(?Announcement $appliedAnn): self
    {
        $this->appliedAnn = $appliedAnn;

        return $this;
    }


}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\AccountType;
use App\Form\RegistrationType;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/registration",name="security_registration")
     */
    public function registration(Request $request, ObjectManager $manager,UserPasswordEncoderInterface $encoder , Filesystem $filesystem)
    {
        $user = new User();

        $form = $this->createForm(RegistrationType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($user,$user->getPassword());
            $user->setPassword($hash);
            $user->setCreatedAt(new \DateTime());
            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('security_login');
        }

        return $this->render('security/registration.html.twig', [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/login",name="security_login");
     */
    public function login(){
        /* Forward to a function in which we define the specefic redirected route depending on the previous paage */
        return $this->render('security/login.html.twig');

    }

    /**
     * @Route("/logout",name="security_logout")
     */
    public function logout(){

    }

    /**
     * @Route("/account/profile",name="account_profile")
     * @return Response
     */
    public function profile(Request $request , ObjectManager $manager , UserPasswordEncoderInterface $encoder ){
        $user = $this->getUser();
        $form = $this->createForm(AccountType::class , $user );
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $manager->persist($user);
            $manager->flush();
            $this->addFlash(
                'success',
                "your Profile is successfuly updated "
            );
            return $this->redirectToRoute('user_show' , ['slug' => $user->getSlug()]);
        }
        return $this->render('security/profile.html.twig',[
            'form'=> $form->createView()
        ]);
    }


}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Login
{% endblock %}



{% block body %}
    <div class="container" style="margin-bottom: 130px; margin-top:100px">
        {% for message in app.session.flashBag.get('error') %}
        <div class="alert alert-danger" style="margin-top: 70px">
           {{ message }}
        </div>
        {% endfor %}
        <form action="{{ path('security_login') }}" method="post">
            <div class="form-group">
                <label for="email">Email :</label>
                <input type="email" class="form-control" placeholder="Email Address..."
                       required name="_username" id="email"></div>
            <div class="form-group">
                <label for="password">Password :</label>
                <input type="password" class="form-control" placeholder="Password"
                       required name="_password" id="password">
            </div>
            <button type="submit" class="btn btn-primary">Login!</button>

        </form>
        <br>
        <p class="text-secondary">You don't have an account ? <a href="{{ path('security_registration') }}"> Create
                one!</a></p>
    </div>
{% endblock %}

templates/security/profile.html.twig
{% extends 'base.html.twig' %}
{% block title %} Modify user profile {% endblock %}
{% block body %}
    <div class="container" style="margin-top: 60px">
        <h1>
            Modify profile
        </h1>

        {{ form_start(form) }}

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary">Save Modification</button>
        {{ form_end(form) }}

    </div>
{% endblock %}

templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Registration
{% endblock %}

{% block body %}
    <div class="container mt-7">

        <div class="bg-light p-3 mb-4">
            <h6>Fill the form to register</h6>
        </div>


        {{ form_start(form) }}

        {{ form_row(form.username,{"label" : "Full Name","attr": {"placeholder":"Enter Your Full Name..."}}) }}
        {{ form_row(form.email,{"attr": {"placeholder":"Enter a valid Email.."}}) }}
        {{ form_row(form.password,{"label":"Password" ,"attr": {"placeholder":"Enter a valid password..."}}) }}
        {{ form_row(form.confirmPassword,{"label":"Password Confirmation","attr": {"placeholder":"Confirm your password..."}}) }}
        {{ form_row(form.phoneNumber,{'attr':{'placeholder':'Enter your Phone number..'}}) }}
        {{ form_row(form.age,{'attr':{'placeholder':'Enter your age...'}}) }}
        {{ form_row(form.profession,{"attr": {"placeholder":"Enter Your Profession..."}}) }}
        {{ form_row(form.image,{'label':'Image' , 'attr' : { 'value' : 'https://i.stack.imgur.com/ZQT8Z.png' }}) }}
        {{ form_row(form.gender) }}
        {{ form_row(form.about,{'label':'Tell us more about yourself','attr':{'placeholder':'Say anything you want ...'}}) }}

        <button type="submit" class="btn btn-primary m-10">Inscription</button>

        {{ form_end(form) }}


   </div>
{% endblock %}