src/Entity/Announcement.php
<?php

namespace App\Entity;

use App\Repository\AnnouncementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert ;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=AnnouncementRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Another announce has already the same title ! please try choosing another one " )
 */
class Announcement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive()
     */
    private $roomNb;

    /**
     * @ORM\Column(type="float")
     * @Assert\GreaterThanOrEqual(50)
     */
    private $surface;

    /**
     * @ORM\Column(type="float")
     *  @Assert\GreaterThanOrEqual(50)
     */
    private $price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $furnished;

    /**
     * @ORM\Column(type="date")
     */
    private $AvailabilityDate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Smoker;

    /**
     * @ORM\Column(type="integer")
     */
    private $maxRoomates;

    /**
     * @ORM\Column(type="boolean")
     */
    private $balcon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $garden;

    /**
     * @ORM\Column(type="boolean")
     */
    private $garage;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="announcements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $locatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="owner")
     * @ORM\JoinColumn(nullable=false)
     */
    private $UserOwner;
    

    /**
     * @ORM\Column(type="datetime")
     */
    private $postedAt;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="Announcement")
     * @Assert\Valid()
     */
    private $imagess;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $CoverImage;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="appliedAnn")
     */
    private $colloc;






    public function __construct()
    {
        $this->imagess = new ArrayCollection();
        $this->userColl = new ArrayCollection();
        $this->colloc = new ArrayCollection();
    }

    /**
     * Permet l'initialisation du slug
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     * @return void
     */

    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRoomNb(): ?int
    {
        return $this->roomNb;
    }

    public function setRoomNb(int $roomNb): self
    {
        $this->roomNb = $roomNb;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFurnished(): ?bool
    {
        return $this->furnished;
    }

    public function setFurnished(bool $furnished): self
    {
        $this->furnished = $furnished;

        return $this;
    }

    public function getAvailabilityDate(): ?\DateTimeInterface
    {
        return $this->AvailabilityDate;
    }

    public function setAvailabilityDate(\DateTimeInterface $AvailabilityDate): self
    {
        $this->AvailabilityDate = $AvailabilityDate;

        return $this;
    }

    public function getSmoker(): ?bool
    {
        return $this->Smoker;
    }

    public function setSmoker(bool $Smoker): self
    {
        $this->Smoker = $Smoker;

        return $this;
    }

    public function getMaxRoomates(): ?int
    {
        return $this->maxRoomates;
    }

    public function setMaxRoomates(int $maxRoomates): self
    {
        $this->maxRoomates = $maxRoomates;

        return $this;
    }

    public function getBalcon(): ?bool
    {
        return $this->balcon;
    }

    public function setBalcon(bool $balcon): self
    {
        $this->balcon = $balcon;

        return $this;
    }

    public function getGarden(): ?bool
    {
        return $this->garden;
    }

    public function setGarden(bool $garden): self
    {
        $this->garden = $garden;

        return $this;
    }

    public function getGarage(): ?bool
    {
        return $this->garage;
    }

    public function setGarage(bool $garage): self
    {
        $this->garage = $garage;

        return $this;
    }

    public function getLocatedAt(): ?City
    {
        return $this->locatedAt;
    }

    public function setLocatedAt(?City $locatedAt): self
    {
        $this->locatedAt = $locatedAt;

        return $this;
    }

    public function getUserOwner(): ?User
    {
        return $this->UserOwner;
    }

    public function setUserOwner(?User $UserOwner): self
    {
        $this->UserOwner = $UserOwner;

        return $this;
    }


    public function getPostedAt(): ?\DateTimeInterface
    {
        return $this->postedAt;
    }

    public function setPostedAt(\DateTimeInterface $postedAt): self
    {
        $this->postedAt = $postedAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImagess(): Collection
    {
        return $this->imagess;
    }

    public function addImagess(Image $imagess): self
    {
        if (!$this->imagess->contains($imagess)) {
            $this->imagess[] = $imagess;
            $imagess->setAnnouncement($this);
        }

        return $this;
    }

    public function removeImagess(Image $imagess): self
    {
        if ($this->imagess->contains($imagess)) {
            $this->imagess->removeElement($imagess);
            // set the owning side to null (unless already changed)
            if ($imagess->getAnnouncement() === $this) {
                $imagess->setAnnouncement(null);
            }
        }

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->CoverImage;
    }

    public function setCoverImage(string $CoverImage): self
    {
        $this->CoverImage = $CoverImage;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getColloc(): Collection
    {
        return $this->colloc;
    }

    public function addColloc(User $colloc): self
    {
        if (!$this->colloc->contains($colloc)) {
            $this->colloc[] = $colloc;
            $colloc->setAppliedAnn($this);
        }

        return $this;
    }

    public function removeColloc(User $colloc): self
    {
        if ($this->colloc->contains($colloc)) {
            $this->colloc->removeElement($colloc);
            // set the owning side to null (unless already changed)
            if ($colloc->getAppliedAnn() === $this) {
                $colloc->setAppliedAnn(null);
            }
        }

        return $this;
    }



}

src/Form/AnnouncementType.php
<?php

namespace App\Form;

use App\Entity\Announcement;
use App\Entity\City;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnnouncementType extends AbstractType
{
    /**
     * @param string $label
     * @param string $placeholder
     * @param array $options
     * @return array
     */
    private function getConfiguration($label,$placeholder,$options = []){
        return array_merge([
            'label'=>$label,
            'attr' =>[
                'placeholder' => $placeholder
            ]
        ],$options);

    }



    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TexTType::class,$this->getConfiguration("Title",'Enter a super title for your announcement'))
            ->add('roomNb',IntegerType::class,$this->getConfiguration('Number of available Rooms','Enter the number of Rooms ',["attr"=>["min"=>"1"]]))
            ->add('surface')
            ->add('price',MoneyType::class,$this->getConfiguration('Price Per Month',"Enter a a price per month"))
            ->add('furnished')
            ->add('AvailabilityDate')
            ->add('Smoker')
            ->add('maxRoomates')
            ->add('balcon')
            ->add('garden')
            ->add('garage')
            ->add('CoverImage' ,UrlType::class,
                $this->getConfiguration('Principal Image Url',
                    'Enter the adresse of the principal cover Image',
                    ['attr' => [
                        'value' => 'http://placehold.it/350x150'
                    ]]))

            ->add('locatedAt' , EntityType::class,[
                'class' => City::class,
                'choice_label' => 'name'
            ])
            ->add('description',TextType::class,$this->getConfiguration('Introduction','A Global description..'))
            ->add('imagess', CollectionType::class,
                [
                    'entry_type'=> ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ]
            ) ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Announcement::class,
        ]);
    }
}

src/Controller/AnnouncementController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Announcement;
use App\Entity\Image;
use App\Form\AdType;
use App\Form\AnnouncementType;
use Container6dcg3sA\getConsole_ErrorListenerService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ObjectManager;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\AnnouncementRepository;
use App\Entity\User;

class AnnouncementController extends AbstractController
{
    /**
     * @Route("/announcement/new", name="new_announcement")
     */
    public function index(Request $request , ObjectManager $manager)
    {
        if( !$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')){
            $session = $request->getSession() ;
            $this->addFlash('error' , 'You need to Log In first !');
            return $this->redirectToRoute('security_login') ;

        }
        $ann = new Announcement() ;

        $form = $this->createForm(AnnouncementType::class , $ann) ;
        $form->handleRequest($request) ;
        if($form->isSubmitted() && $form->isValid()){
            foreach ($ann->getImagess() as $image){
                $image->setAd($ann);
                $manager->persist($image);
            }
            $user = $this->getUser() ;
            $ann->setUserOwner($user) ;
            
            $ann->setPostedAt(new \DateTime()) ;
            $city = $ann->getLocatedAt() ;
            $city->setAvgPrice(($city->getAvgPrice()*$city->getNbAnnouncements()+$ann->getPrice())/($city->getNbAnnouncements()+1)) ;
            $city->setNbAnnouncements($city->getNbAnnouncements()+1) ;
            $user->addAnnouncement($ann) ;
            $manager->persist($user) ;
            $manager->persist($city);
            $manager->persist($ann) ;
            $manager->flush();
            $this->addFlash(
                'success',
                "Your announce <strong>{$ann->getTitle()}</strong> Has been successfully added"
            );

            return $this->redirectToRoute('ads_show',['slug'=>$ann->getSlug()]);
            //return $this->redirectToRoute('home') ;
        }

        return $this->render('announcement/index.html.twig', [
            'controller_name' => 'AnnouncementController',
            'ad' => $ann ,
            'form' => $form->createView()
        ]);
    }
    /**
     * @Route("/announcement/{slug}/edit", name="ads_edit")
     */
    public function edit(Request $request , ObjectManager $manager,Announcement $ann)
    {
        if( !$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')){
            $session = $request->getSession() ;
            $this->addFlash('error' , 'You need to Log In first !');
            return $this->redirectToRoute('security_login') ;

        }
        $form = $this->createForm(AnnouncementType::class , $ann) ;
        $form->handleRequest($request) ;
        if($form->isSubmitted() && $form->isValid() ){
            foreach ($ann->getImagess() as $image){
                $image->setAd($ann);
                $manager->persist($image);
            }
            //$user = $this->getUser() ;
           // $ann->setUserOwner($user) ;

            $ann->setPostedAt(new \DateTime()) ;
            $city = $ann->getLocatedAt() ;
            $city->setAvgPrice(($city->getAvgPrice()*$city->getNbAnnouncements()+$ann->getPrice())/($city->getNbAnnouncements()+1)) ;
            $city->setNbAnnouncements($city->getNbAnnouncements()+1) ;
           // $user->addAnnouncement($ann) ;
            //$manager->persist($user) ;
            $manager->persist($city);
            $manager->persist($ann) ;
            $manager->flush();
            $this->addFlash(
                'success',
                "Your announce <strong>{$ann->getTitle()}</strong> Has been successfully Modified"
            );

            return $this->redirectToRoute('ads_show',['slug'=>$ann->getSlug()]);
            //return $this->redirectToRoute('home') ;
        }


        return $this->render('announcement/edit.html.twig', [
            'controller_name' => 'AnnouncementController',
            'ad' => $ann ,
            'form' => $form->createView()
        ]);
    }








    /**
     * @Route("/ads", name="ads_index")
     */
    public function indexTo(AnnouncementRepository $repository)
    {
        $ads = $repository->findAll();

        return $this->render('announcement/indexTo.html.twig', [
            'ads' => $ads,
        ]);
    }

    private function searchArray($arr , $obj){
        $obj1=null;
        foreach($arr as $obj1 )
            if($obj1===$obj) return true ;
        else
            return false ;
    }



    /**
     * @Route("announcement/apply/{slug}", name="ad_apply" )
     */
    public function apply($slug, AnnouncementRepository $repo ,Request $request , ObjectManager $manager ){
        if( !$this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')){
            $session = $request->getSession() ;
            $this->addFlash('error' , 'You need to Log In first !');
            return $this->redirectToRoute('security_login') ;

        }
        
        $ad=$repo->findOneBySlug($slug) ;
        $user=$this->getUser();
        if( (count($ad->getColloc()) < $ad->getMaxRoomates()) && !$user->getAppliedAnn()){
            $ad->addColloc($user) ;
            $user->setAppliedAnn($ad) ;
            $this->addFlash('application' , 'Your application is saved successfully !');
            $manager->persist($ad) ;
            $manager->persist($user) ;
            $manager->flush() ;
            return $this->redirectToRoute('ads_show' , ['slug' => $slug]) ;
        }
        $this->addFlash('error2' , 'You have already applied to an announcement !');
        return $this->redirectToRoute('ads_show' , ['slug' => $slug]) ;


    }
    /**
     * @Route("/announcement/{slug}",name="ads_show")
     *
     */
    public function show($slug, AnnouncementRepository $repository ){
        $ad = $repository->findOneBySlug($slug);
        $ads = $repository->findAll() ;
        $int = 0 ;
        foreach($ads as $add){
            if ($add->getUserOwner() === $ad->getUserOwner())
            $int++ ;
        }

        return $this->render('announcement/show.html.twig',[
            'ad'=>$ad ,
            'int' =>$int
        ]);
    }
}

templates/announcement/_ad.html.twig
{% set url = path('ads_show',{"slug": ad.slug}) %}
                <div class="col-md-4">
                    <div class="card bg-light border-secondary mb-3">
                        <div class="card-header text-center">
                            {{ ad.roomNb }} rooms, <strong> {{ ad.price }} DT/Month </strong> <br>
                            <small>Not yet rated</small>
                        </div>
                        <a href="{{ url }}" style="max-width: 348px">
                            <img src="{{ ad.coverImage }}" alt="coverImageLoading"
                                 style="max-width: 348px;min-height: 250px" class="thumbnail img-fluid">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{{ url }}">
                                    {{ ad.title }}
                                </a>
                            </h4>
                            <hr>
                            <p class="card-text">
                                {{ ad.description | slice(3,100) }}
                            </p>
                            <a href="{{ url }}" class="btn btn-info">Learn more..</a>

                        </div>
                    </div>
                </div>

templates/announcement/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h2 style="margin-top: 70px">Change your Announcement</h2>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">Save changes</button>
        {{ form_end(form) }}
    </div>
{% endblock %}
{#
{% block title %}
    Edit Announce
{% endblock %}

{% form_theme form _self %}

{% block body %}

    <div class="container bg-light">
        <p></p>
        <h2 class="my-5">Modify Your announce : {{ ad.title }}</h2>

        {{ form_start(form) }}
        <div class="row">
            <div class="col">
                <div class="alert alert-secondary">
                    <h3>General informations</h3>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.roomNb) }}
                    {{ form_row(form.surface) }}
                    {{ form_row(form.AvailabilityDate) }}
                    {{ form_row(form.locatedAt) }}

                </div>
                <div class="alert alert-secondary">
                    <h3>Announce details</h3>
                    <hr>
                    {{ form_row(form.maxRoomates) }}
                    {{ form_row(form.balcon) }}
                    {{ form_row(form.garden) }}
                    {{ form_row(form.garage) }}
                    {{ form_row(form.furnished) }}
                    {{ form_row(form.Smoker) }}
                    {{ form_row(form.description) }}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-secondary">
                    <h3>Announce Images</h3>
                    <hr>
                    {{ form_row(form.CoverImage) }}
                    {{ form_row(form.imagess) }}
                </div>
            </div>
        </div>

        <div class="alert alert-success clearfix">
            <h3>Save and Display my Announce</h3>
            <p><strong>Your are going to make your announcement online. Please make sure your data is valid and correct before submitting </strong></p>
            <button type="submit"
                    class="btn btn-lg btn-primary float-right"> {{ button|default('Modify My announce') }} &nbsp; <i
                        class="fa fa-share"></i></button>
        </div>
        {{ form_end(form) }}

    </div>
{% endblock %}

{% block _announcement_imagess_widget %}
    <p>Click to add Images!</p>
    {{ form_widget(form) }}

    <input type="hidden" id="widget-counter" value="0">

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Add Image</button>
    </div>
    {{ form_end(form) }}
{% endblock %}


{% block _announcement_imagess_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _announcement_imagess_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col-8">{{ form_widget(form.url) }}</div>
                    <div class="col-4">{{ form_widget(form.caption) }}</div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $('#add-image').click(function () {
            // on recupére le nombre de futurs champs crées
            const index = +($('#widget-counter').val());

            //on récupére les prototype des entrées
            const tmpl = $('#announcement_imagess').data('prototype').replace(/__name__/g, index);

            // on fait l'injection du code au sein de la div
            $('#announcement_imagess').append(tmpl);

            $('#widget-counter').val(index+1)

            // gestion de bouton supprimer
            handleDeleteButtons();

        });

        function updateCounter() {
            const count = +$('#ad_images div.form-group').length;

            $('#widget-counter').val(count);

        }
        updateCounter();
        function handleDeleteButtons() {
            $('button[data-action="delete"]').click(function () {
                const target = this.dataset.target;
                $(target).remove();

            })
        }
        handleDeleteButtons();

    </script>
{% endblock %}
#}

templates/announcement/indexTo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offers{% endblock %}

{% block body %}
    <div class="container" style="margin-top: 70px">
        <h2 class="my-2">Our Hosts offers</h2>
        <p></p>

        <div class="row">
            {% for ad in ads %}
                {% include "announcement/_ad.html.twig" %}
            {% endfor %}

        </div>
    </div>

{% endblock %}

templates/announcement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}


    <div class="adtitle"
         style="background-image: url({{ ad.coverImage }});background-size: cover;background-position:center ; margin-top: 70px">
        <div class="container py-4 my-3">
            <h2>{{ ad.title }}</h2>
            <p>{{ ad.description | slice(3,100)}}</p>
            <p class="h2">
                <strong> {{ ad.roomNb }} rooms </strong> for <strong>{{ ad.price }}DT/Month</strong>
            </p>
            {% if app.user != ad.userOwner  %}
            <a href="{{ path('ad_apply' , {"slug" : ad.slug}) }}" class="btn btn-secondary">Apply!</a>
            {% else %}
                <a href="{{ path('ads_edit' , {"slug" : ad.slug}) }}" class="btn btn-secondary">Change it!</a>
            {% endif %}
        </div>

    </div>

    <div class="container">
        {% for message in app.session.flashBag.get('application') %}
            <div class="alert alert-success" >
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.session.flashBag.get('error2') %}
            <div class="alert alert-danger" >
                {{ message }}
            </div>
        {% endfor %}
        <div class="row">

            {# Announce description #}
            <div class="col-md-8 mb-3">
                {{ ad.description | raw }}
                {# carousel #}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.imagess %}
                            <li data-target="#carouselExampleIndicators"
                                data-slide-to="{{ loop.index0 }}nth" {% if loop.first %}
                                class="active"> {% endif %}</li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.imagess %}
                            <div class="carousel-item {% if loop.first %} active {% endif %}">
                                <img class="d-block w-100 " src="{{ image.url }}" alt="{{ loop.index0 }} slide">

                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>

                            </div>
                        {% endfor %}

                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>


            </div>
            {# user description #}
            <div class="col">
                <div class="row my-3">
                    <div class="col-4">
                        <img src="{{ad.userOwner.image}}" alt="Avatar"  >
                    </div>
                    <div class="col" style="margin-left : 30px">
                        <h3>{{ad.userOwner.username }}</h3>
                        <span class="badge badge-primary">{{int }} Announcements</span>
                    </div>
                </div>
                <p>{{ad.userOwner.about}}</p>
            </div>

        </div>
        <h4>You can see the applied users for this house :</h4>
        {% for user in ad.colloc %}
            <div class="col-md-4">
                <div class="card bg-light border-secondary mb-3" >
                    <div class="card-header text-center">
                         <strong> {{ user.username }}</strong> <br>

                    </div>
                        <img src="{{ user.image }}" alt="coverImageLoading"
                             style="width: fit-content;height:fit-content ; border-radius: 50%" class="thumbnail img-fluid" >
                    </a>
                    <div class="card-body">
                        <h4 class="card-title">
                                {{ user.phoneNumber }}
                        </h4>
                        <hr>
                        <p class="card-text">
                            {{ user.about | slice(3,100) }}
                        </p>
                        <a href="{{ path('user_show' , {'slug' : user.slug}) }}" class="btn btn-info">Learn more..</a>

                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}